### ISSUE TITLE
RT UK is unavailable

### ISSUE THREAD

**Issue by ExperiencersInternational** [ExperiencersInternational/tvsetup#2]
https://rt-uk.rttv.com/live/rtuk/playlist.m3u8

Stream does not load. Will be removing it from its spot at channel 807 for now.

Alternative streams are recommended.

**Comment by dp247** [comment]
Think it was changed to this:
https://rt-glb.rttv.com/live/rtnews/playlist.m3u8

**Comment by ExperiencersInternational** [comment]
Thank you!
