### ISSUE TITLE
[📺 Broken Stream]: Various channels

### ISSUE THREAD

**Issue by ExperiencersInternational** [ExperiencersInternational/tvsetup#26]
### Broken channel numbers

I'm gonna ignore this

### What happened to the stream?

Not loading

### Additional information

Sorry for the lack of a description, I had this filed in recently from someone who went to my website and I haven't had the chance to check yet! I'm opening this issue just to make sure that this is known about.

![Screenshot_2023-10-02-13-59-40-874_com google android gm](https://github.com/ExperiencersInternational/tvsetup/assets/56035537/8119a1ab-ef9f-4b7d-a472-4c6f03501814)

### To prevent spam reports, we need to know whether you are viewing within the UK. The majority of channels are unavailable to viewers outside of the UK, and they may be unavailable to viewers using a Virtual Private Network. We also ask you to check that a stream works within VLC, since it may be an issue with your application.

- [X] I'm watching within the UK, and I'm not using a VPN
- [X] I've checked that the stream does not load in VLC

**Comment by oatmealm** [comment]
I'm guessing it might be that they're encrypted? I was mostly using channel 4/e4 and Dave over vpn, not uk, and it was fine. BBCs never worked.

**Comment by ExperiencersInternational** [comment]
@oatmealm if you're using a VPN, the stream that you're using may block connections from them

**Comment by oatmealm** [comment]
It used to work over vpn for months now, but then stopped a week ago. It's seem to work again now 🙏 did you change anything on your side?

**Comment by ExperiencersInternational** [comment]
> It used to work over vpn for months now, but then stopped a week ago. It's seem to work again now 🙏 did you change anything on your side?

Unless @dp247 changed anything, I haven't touched the GitHub repository in a while to be completely honest. I don't operate any of the streams that we link to nor do I have any affiliation with them btw.

**Comment by dp247** [comment]
> > It used to work over vpn for months now, but then stopped a week ago. It's seem to work again now 🙏 did you change anything on your side?
> 
> Unless @dp247 changed anything, I haven't touched the GitHub repository in a while to be completely honest. I don't operate any of the streams that we link to nor do I have any affiliation with them btw.

Nah, last commit was on August 1st hehe

**Comment by dp247** [comment]
I'll check out those BBC channels though - there were some updates recently.

**Comment by oatmealm** [comment]
Any idea what happens to the aljazeera English Channel?

**Comment by ExperiencersInternational** [comment]
@oatmealm tbh I didn't realise that got deleted, there might not be any better known stream at the moment

I'm still waiting for when all ITV channels work properly again lol
