### ISSUE TITLE
BBC1 & BBC2 not 720p as listed.

### ISSUE THREAD

**Issue by timboxyz** [ExperiencersInternational/tvsetup#32]
### Broken channel numbers

1,2

### What happened to the stream?

Other

### Additional information

These channels load as 540p not 720p. Given that regional variations e.g. BBC London are available as 540p to enable viewing regional optouts and that 1080p is available on both the main channels the choice of SD seems odd.

### To prevent spam reports, we need to know whether you are viewing within the UK. The majority of channels are unavailable to viewers outside of the UK, and they may be unavailable to viewers using a Virtual Private Network. We also ask you to check that a stream works within VLC, since it may be an issue with your application.

- [X] I'm watching within the UK, and I'm not using a VPN
- [X] I've checked that the stream does not load in VLC

**Comment by dp247** [comment]
The BBC streams have always been 720p online, and the .mpd ones still are. Not sure why the m3u8 ones are 540p, but these are the iPlayer streams taken from the BBC API, so not much we can do really.

**Comment by ExperiencersInternational** [comment]
Just been going through the channels and I'm pretty sure they were 720p previously, but I guess they are 540p now.

I don't particularly want to use MPD versions as the primary ones as they have limited support by some apps (VLC loads them, but I'm not sure what else does)

**Comment by ExperiencersInternational** [comment]
Also, the list hasn't been accurate for a bit, I don't watch a lot of TV so a lot of information may be missing at times

**Comment by dp247** [comment]
The API says that the status is deprecated, so might die sooner or later lol

**Comment by timboxyz** [comment]
In my experience, playing from iPlayer the resolution you get depends upon your device. Tablet always gets SD via the app. PC gets HD via a web browser.

**Comment by dp247** [comment]
> In my experience, playing from iPlayer the resolution you get depends upon your device. Tablet always gets SD via the app. PC gets HD via a web browser.

I don't disagree, though iPlayer uses the .mpd file so is able to switch between 360p/720p rather than 244p/540p I guess.
