### ISSUE TITLE
[📺 Broken Stream]: QVC

### ISSUE THREAD

**Issue by ExperiencersInternational** [ExperiencersInternational/tvsetup#33]
### Broken channel numbers

16

### What happened to the stream?

Not loading

### Additional information

Good old QVC isn't working.

![image](https://github.com/ExperiencersInternational/tvsetup/assets/56035537/884f1951-91f5-411e-9e8c-a262f49dc31f)

### To prevent spam reports, we need to know whether you are viewing within the UK. The majority of channels are unavailable to viewers outside of the UK, and they may be unavailable to viewers using a Virtual Private Network. We also ask you to check that a stream works within VLC, since it may be an issue with your application.

- [X] I'm watching within the UK, and I'm not using a VPN
- [X] I've checked that the stream does not load in VLC

**Comment by dp247** [comment]
Fixed >:)
