### ISSUE TITLE
[📺 Broken Stream]: 

### ISSUE THREAD

**Issue by superray2** [ExperiencersInternational/tvsetup#36]
### Broken channel numbers

233,236

### What happened to the stream?

Not loading

### To prevent spam reports, we need to know whether you are viewing within the UK. The majority of channels are unavailable to viewers outside of the UK, and they may be unavailable to viewers using a Virtual Private Network. We also ask you to check that a stream works within VLC, since it may be an issue with your application.

- [X] I'm watching within the UK, and I'm not using a VPN
- [X] I've checked that the stream does not load in VLC

**Comment by dp247** [comment]
233 is def working today if you try it again. 236 died, so I've replaced it.
