### ISSUE TITLE
[📺 Broken Stream]: Numerous broken channels

### ISSUE THREAD

**Issue by dazzza19** [ExperiencersInternational/tvsetup#38]
### Broken channel numbers

Most channels with the exception of the bbc channels not working 

### What happened to the stream?

Not loading

### To prevent spam reports, we need to know whether you are viewing within the UK. The majority of channels are unavailable to viewers outside of the UK, and they may be unavailable to viewers using a Virtual Private Network. We also ask you to check that a stream works within VLC, since it may be an issue with your application.

- [X] I'm watching within the UK, and I'm not using a VPN
- [X] I've checked that the stream does not load in VLC

**Comment by dp247** [comment]
I'll update the channels should they become available, but this is how it is for now.

**Comment by ExperiencersInternational** [comment]
Yeah I received an email about this but couldn't be bothered to make a full report

**Comment by ExperiencersInternational** [comment]
> Yeah I received an email about this but couldn't be bothered to make a full report on Christmas Day

Here's the email I received:

"Hey, its me again so there are a few problems with your m3u. One of them is that the e4 extra stream is the same as e4+1 and itv1+1 is the same as itv1 but 2 hours behind. Another is that there is a duplicate bbc scotland P.S horror extra got rebranded to legend extra so the name needs changing in the m3u.

Another problem is that there is possibly channels that are offline and ill list them below:
qvc style
qvc beauty
pbs america
bbc radio 1
bbc radio 2
bbc radio 3
bbc radio 4
bbc radio 5 live
bbc radio 5 live sports extra
bbc radio 6 music
bbc radio 4 extra
bbc radio asian network
all the regional bbc radio stations
bbc radio 1 dance
bbc radio 1 relax
cbeebies radio
greatest hits radio
france 24
all the music channels owned by channel 4 (official streams closed down in november)
bloomberg
stv+1
bbc alba
bbc news (alt stream)"

**Comment by dazzza19** [comment]
No worries, I appreciate the work that is done, I do have some alternatives for the bbc radio stations I'll send them when I get home

**Comment by U53R3RR0R** [comment]
I'm sure you're aware of.this but I can't get any ITV, Channel 4 or Channel 5 streams to work.

**Comment by dp247** [comment]
> I'm sure you're aware of.this but I can't get any ITV, Channel 4 or Channel 5 streams to work.

Yes, most of the streams are broken

**Comment by ExperiencersInternational** [comment]
> I'm sure you're aware of.this but I can't get any ITV, Channel 4 or Channel 5 streams to work.

If we get any sources for those channels, we will update as soon as we can. It's just a pain considering sources constantly keep popping up and going.

**Comment by dp247** [comment]
I found some, guess I'll fix tomorrow (including the radio streams)

**Comment by ExperiencersInternational** [comment]
> I found some, guess I'll fix tomorrow (including the radio streams)

This game is practically whack-a-mole lol

**Comment by ExperiencersInternational** [comment]
Didn't realise I could edit OP, going to make it more clearer for people reading

**Comment by ExperiencersInternational** [comment]
> > I found some, guess I'll fix tomorrow (including the radio streams)
> 
> Thanks so much! This is the cleanest IPTV playlist for Freeview channels I could find anywhere. Looking forward to having it back up and running so I can use it for the first time!
> 
> Anyone know why issues with playlists like this are common? Is it providers revoking their streams, for example?

Thanks!

I will admit I don't do a lot of work now here (especially considering I don't tend to watch TV), but I wanted to make something that was easy to understand compared to other playlists.

Other playlists have channels literally positioned everywhere, they don't tend to use tvg-chno though.

I think sources are probably either revoking streams because of DMCA takedowns from copyright owners or the fact that people are able to access it when they're not supposed to be (some of these things are subscription based unfortunately).

I'm hoping that Digital UK (that's the right name right?) eventually releases Freely, since that would be the best solution.

**Comment by Venngeance** [comment]
Hi there @dp247 - I was curious to learn how you were progressing! It seems you might be our only hope right about now to get these channels back up and running.

**Comment by dazzza19** [comment]
Hi, where is the best place to send you a link to working BBC radio stations. It's on GitHub. Thanks dazzza

**Comment by dp247** [comment]
> This game is practically whack-a-mole lol
My favorite kind of game 😊

> Hi there @dp247 - I was curious to learn how you were progressing! It seems you might be our only hope right about now to get these channels back up and running.
Gimme an hour. I'll sort it now

> Hi, where is the best place to send you a link to working BBC radio stations. It's on GitHub. Thanks dazzza
Here or Pastebin, whichever is easiest

**Comment by dazzza19** [comment]
Hi, I found these links to BBC radio stations on GitHub they aren't my work and the link to the  page is.
https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3

**Comment by ExperiencersInternational** [comment]
> Hi, I found these links to BBC radio stations on GitHub they aren't my work and the link to the page is. https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3

Thank you! I'm not at a computer right now and I don't particularly feel like doing this on my phone so you'll have to wait for a little.

**Comment by dp247** [comment]
> > Hi, I found these links to BBC radio stations on GitHub they aren't my work and the link to the page is. https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3
> 
> Thank you! I'm not at a computer right now and I don't particularly feel like doing this on my phone so you'll have to wait for a little.

I saved you the local radio ones :p

**Comment by dp247** [comment]
Some of the channels may vary, it's the nature of this unfortunately but I'll keep my eyes around for any better sources hehe

**Comment by Venngeance** [comment]
@dp247 You're a hero. My wife can now record Road Wars and is very happy indeed. Have a great weekend.

**Comment by dp247** [comment]
> @dp247 You're a hero. My wife can now record Road Wars and is very happy indeed. Have a great weekend.

Thank you! I'll plug my free [EPG](https://github.com/dp247/Freeview-EPG) while I'm here haha

**Comment by Venngeance** [comment]
> > @dp247 You're a hero. My wife can now record Road Wars and is very happy indeed. Have a great weekend.
> 
> Thank you! I'll plug my free [EPG](https://github.com/dp247/Freeview-EPG) while I'm here haha

I use it with Emby and it works great! Highly recommend.

**Comment by ExperiencersInternational** [comment]
> > @dp247 You're a hero. My wife can now record Road Wars and is very happy indeed. Have a great weekend.
> 
> Thank you! I'll plug my free [EPG](https://github.com/dp247/Freeview-EPG) while I'm here haha

It is in the readme.md file already 😄

Shame I can't record stuff on my setup, have to deal with hoping that my terrestrial signal is well enough to record

> > > @dp247 You're a hero. My wife can now record Road Wars and is very happy indeed. Have a great weekend.
> > 
> > 
> > Thank you! I'll plug my free [EPG](https://github.com/dp247/Freeview-EPG) while I'm here haha
> 
> I use it with Emby and it works great! Highly recommend.

Tried the repo a while ago with Jellyfin and it's not the best experience there, glad it works on Emby though

**Comment by dp247** [comment]
> Tried the repo a while ago with Jellyfin and it's not the best experience there, glad it works on Emby though
Was it the blank EPG issue?

**Comment by ExperiencersInternational** [comment]
> > Tried the repo a while ago with Jellyfin and it's not the best experience there, glad it works on Emby though
> 
> Was it the blank EPG issue?

Nah it wasn't that, some channels weren't ordered correctly etc

**Comment by dp247** [comment]
Gotcha, its on the list :p

**Comment by notgoingout** [comment]
Most of the channels are working again. Brilliant. Thank you so much for the work to put it up and running again. 
Greatly appreciated. Hope we can enjoy it for a while :) Thanks a million
