### ISSUE TITLE
[📺 Broken Stream]: Most channels not working

### ISSUE THREAD

**Issue by j-leist** [ExperiencersInternational/tvsetup#39]
### Broken channel numbers

All

### What happened to the stream?

Not loading

### Additional information

Only able to access BBC channels ‘can’t open stream’ on most of them 

### To prevent spam reports, we need to know whether you are viewing within the UK. The majority of channels are unavailable to viewers outside of the UK, and they may be unavailable to viewers using a Virtual Private Network. We also ask you to check that a stream works within VLC, since it may be an issue with your application.

- [X] I'm watching within the UK, and I'm not using a VPN
- [X] I've checked that the stream does not load in VLC

**Comment by dp247** [comment]
Please see #38.
