### ISSUE TITLE
All ITV Channels down again

### ISSUE THREAD

**Issue by MrMussa** [ExperiencersInternational/tvsetup#6]
All ITV channels are down together with the BBC 1&2 Channels. If someone has an idea of how to fix this, please tell us ASAP.

**Comment by MrMussa** [comment]
![Screenshot_20230330_152602_IPTV Player](https://user-images.githubusercontent.com/129394688/228835399-2b8de840-5afa-420b-83ce-afd0382e5399.jpg)


This is what I am talking about, guys.

**Comment by MrMussa** [comment]
When even the timeshift service fails to work (+1), you know somethin's gone bad. Please, anyone?

**Comment by ExperiencersInternational** [comment]
Didn't realise BBC channels were down, but I do know about the majority of channels being down.

The problem is that I don't think IPTV-org has changed anything since they got taken down

For ITV1, STV still works.
