### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by dp247** [ExperiencersInternational/tvsetup#9]
Just wanted to let you know, I built an XMLTV EPG to match this project 😄
https://github.com/dp247/Freeview-EPG

**Comment by ExperiencersInternational** [comment]
Seriously, thank you so much for all the help.

One thing I will warn you is that IPTV-org/EPG was apparently banned for using Actions too much

**Comment by ExperiencersInternational** [comment]
I can't take screenshots due to stupid security restrictions but I think the timings might be 1 hour ahead of what's being actually shown, e.g. showing Loose Women is showing on ITV1 rn when in reality it's This Morning

**Comment by dp247** [comment]
> I can't take screenshots due to stupid security restrictions but I think the timings might be 1 hour ahead of what's being actually shown, e.g. showing Loose Women is showing on ITV1 rn when in reality it's This Morning
> 
> nvm you already know

I'm gonna blame github for that 😅

**Comment by ExperiencersInternational** [comment]
I think I can set some sort of override with timeshift but I'd rather see whether the actual XML can be fixed

**Comment by dp247** [comment]
I think I got it, had to readd the xml and refresh to make it work on Plex at least

**Comment by ExperiencersInternational** [comment]
wait, Plex has an IPTV thing? im using Cosmi TV and it's a pain to refresh stuff

**Comment by dp247** [comment]
Kind of, I have xTeVe and Plex on an Unraid server - xTeVe does the IPTV mapping and can build an EPG for Plex
